accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'), 
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<username>/', views.profile, name='profile'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model


class CustomUserCreationForm(UserCreationForm):
    
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = UserCreationForm.Meta.fields + ('email', )


class CustomUserChangeForm(UserChangeForm):
    
    class Meta:
        model = get_user_model()
        fields = ('email', 'first_name', 'last_name', )

accounts/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import login as auth_login, logout as auth_logout, update_session_auth_hash, get_user_model
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from .forms import CustomUserCreationForm, CustomUserChangeForm


@require_http_methods(['GET', 'POST'])
def login(request):
    if request.user.is_authenticated:
        return redirect('articles:index')
    if 'POST' == request.method:
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect(request.GET.get('next') or 'articles:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)


@require_POST
def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('articles:index')


@require_http_methods(['GET', 'POST'])
def signup(request):
    if 'POST' == request.method:
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('articles:index')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/signup.html', context)


@require_POST
def delete(request):
    if request.user.is_authenticated:
        request.user.delete()
        auth_logout(request)
    return redirect('articles:index')


@login_required
@require_http_methods(['GET', 'POST'])
def update(request):
    if 'POST' == request.method:
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/update.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def change_password(request):
    if 'POST' == request.method:
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/change_password.html', context)


def profile(request, username):
    person = get_object_or_404(get_user_model(), username=username)
    context = {
        'person': person,
    }
    return render(request, 'accounts/profile.html', context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        person = get_object_or_404(get_user_model(), pk=user_pk)
        if person != request.user:
            if person.followers.filter(pk=request.user.pk).exists():
                person.followers.remove(request.user)
            else:
                person.followers.add(request.user)
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1>PASSWORD</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">SUBMIT</button>
</form>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>LOGIN</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">SUBMIT</button>
</form>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ person.username }}님의 프로필</h1><hr>
<!-- 팔로우 -->
{% with followers=person.followers.all followings=person.followings.all %}
  <div>
    <div>
      팔로워: {{ followers|length }} / 팔로잉: {{ followings|length }}
    </div>
    {% if user != person %}
      <form action="{% url 'accounts:follow' person.pk %}" method="post">
        {% csrf_token %}
        {% if user in followers %}
          <button type="submit">UNFOLLOW</button>
        {% else %}
          <button type="submit">FOLLOW</button>
        {% endif %}
      </form>
    {% endif %}
  </div>
{% endwith %}
<!-- 작성 게시글 목록 -->
<h3>{{ person.username }}'s 게시글</h3>
{% for article in person.article_set.all %}
  <div><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></div>
{% endfor %}
<hr>
<!-- 작성 댓글 목록-->
<h3>{{ person.username }}'s 댓글</h3>
{% for comment in person.comment_set.all %}
  <div>{{ comment.content }}</div>
{% endfor %}
<hr>
<!-- 좋아요 게시글 목록 -->
<h3>{{ person.username }}'s 좋아요한 게시글</h3>
{% for article in person.like_articles.all %}
  <div><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></div>
{% endfor %}
<hr>
<!-- 뒤로가기 버튼 -->
<a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>SIGNUP</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">SUBMIT</button>
</form>
{% endblock %}

templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<h1>MODIFY</h1>
<form action="" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">SUBMIT</button>
</form>
{% endblock %}