accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'), 
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<username>/', views.profile, name='profile'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:article_pk>/', views.detail, name='detail'),
    path('<int:article_pk>/delete/', views.delete, name='delete'),
    path('<int:article_pk>/update/', views.update, name='update'),
    path('<int:article_pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:article_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/likes/', views.likes, name='likes'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles')
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = ('title', 'content',)


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        exclude = ('article', 'user',)

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST, require_safe
from .models import Article, Comment
from .forms import ArticleForm, CommentForm


@require_safe
def index(request):
    articles = Article.objects.order_by('-pk')
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    if 'POST' == request.method:
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'articles/create.html', context)

@require_safe
def detail(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form': comment_form,
        'comments': comments,
    }
    return render(request, 'articles/detail.html', context)


@require_POST
def delete(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user.is_authenticated:
        if request.user == article.user:
            article.delete()
            return redirect('articles:index')
    return redirect('articles:detail', article.pk)


@login_required
@require_http_methods(['GET', 'POST'])
def update(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)
    if request.user == article.user:
        if 'POST' == request.method:
            form = ArticleForm(request.POST, instance=article)
            if form.is_valid():
                form.save()
                return redirect('articles:detail', article_pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:index')
    context = {
        'form': form,
        'article': article,
    }
    return render(request, 'articles/update.html', context)


@require_POST
def comments_create(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = article
            comment.user = request.user
            comment.save()
        return redirect('articles:detail', article.pk)
    return redirect('accounts:login')


@require_POST
def comments_delete(request, article_pk, comment_pk):
    if request.user.is_authenticated:
        comment = get_object_or_404(Comment, pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('articles:detail', article_pk)


@require_POST
def likes(request, article_pk):
    if request.user.is_authenticated:
        article = get_object_or_404(Article, pk=article_pk)
        if article.like_users.filter(pk=request.user.pk).exists():
            article.like_users.remove(request.user)
        else:
            article.like_users.add(request.user)
        return redirect('articles:detail', article.pk)
    return redirect('accounts:login')

templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
<h1>CREATE</h1>
<form action="{% url 'articles:create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">SUBMIT</button>
</form>
<a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}

templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>DETAIL</h1>
<div>
  <!-- 게시글 -->
  <p>{{ article.pk }}</p>
  <p>{{ article.title }}</p>
  <p>{{ article.content }}</p>
  <p>{{ article.created_at }}</p>
  <p>{{ article.updated_at }}</p>
  <!-- 좋아요 버튼 -->
  <form action="{% url 'articles:likes' article.pk %}" method="post">
    {% csrf_token %}
    {% if user in article.like_users.all %}
      <button type="submit">DISLIKE</button>
    {% else %}
      <button type="submit">LIKE</button>
    {% endif %}
  </form>
  <!-- 게시글 수정, 삭제 버튼 -->
  {% if user == article.user %}
    <a href="{% url 'articles:update' article.pk %}">UPDATE</a>
    <form action="{% url 'articles:delete' article.pk %}" method="post">
      {% csrf_token %}
      <button type="submit">DELETE</button>
    </form>
  {% endif %}
  <!-- 뒤로가기 버튼 -->
  <a href="{% url 'articles:index' %}">BACK</a>
  <!-- 댓글 -->
  <h4>댓글 목록</h4>
  {% if comments %}
    <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
  {% endif %}
  <ul>
    {% for comment in comments %}
      <li>{{ comment.user }} - {{ comment.content }}</li>
      <!-- 댓글 삭제 버튼 -->
      {% if user == comment.user %}
        <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="post">
          {% csrf_token %}
          <button type="submit">DELETE</button>
        </form>
      {% endif %}
    {% empty %}
      <p>댓글이 없습니다.</p>
    {% endfor %}
  </ul>
  <!-- 댓글 작성 -->
  {% if request.user.is_authenticated %}
    <form action="{% url 'articles:comments_create' article.pk %}" method="post">
      {% csrf_token %}
      {{ comment_form }}
      <button type="submit">SUBMIT</button>
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">댓글을 작성하려면 로그인하세요.</a>
  {% endif %}
</div>
{% endblock %}

templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
<h1>INDEX</h1>
{% for article in articles %}
  <p><a href="{% url 'accounts:profile' article.user.username %}">{{ article.user }}</a></p>
  <p><a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a></p>
  <p>{{ article.content }}</p><hr>
{% endfor %}
{% if user.is_authenticated %}
  <a href="{% url 'articles:create' %}">CREATE</a>
{% else %}
  <a href="{% url 'accounts:login' %}">[새 글을 작성하려면 로그인]</a>
{% endif %}
{% endblock %}

templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
<h1>UPDATE</h1>
<form action="{% url 'articles:update' article.pk %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">SUBMIT</button>
</form>
<a href="{% url 'articles:index' %}">BACK</a>
{% endblock %}