accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'), 
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    path('<username>/', views.profile, name='profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Articles</title>
</head>
<body>
  {% if user.is_authenticated %}
    <h3>{{ user }}님, 안녕하세요.</h3>
    <a href="{% url 'accounts:profile' user.username %}">내 프로필</a>
    <form action="{% url 'accounts:logout' %}" method="post">
      {% csrf_token %}
      <button type="submit">LOGOUT</button>
    </form>
    <a href="{% url 'accounts:update' %}">MODIFY</a>
    <form action="{% url 'accounts:delete' %}" method="post">
      {% csrf_token %}
      <button type="submit">SIGNOUT</button>
    </form>
  {% else %}
    <a href="{% url 'accounts:login' %}">LOGIN</a>
    <a href="{% url 'accounts:signup' %}">SIGNUP</a>
  {% endif %}
  {% block content %}
  {% endblock %}
</body>
</html>